# Generated by Django 2.2.7 on 2019-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.CharField(choices=[('0', '失效'), ('1', '有效')], default='1', max_length=10),
        ),
    ]
